---
- name: "Create the gitlab_runner volume"
  become: yes
  containers.podman.podman_volume:
    name: "gitlab-runner-config"

- name: "Inspect the volumes"
  become: yes
  containers.podman.podman_volume_info:
    name: "gitlab-runner-config"
  register: volume_state

- debug:
    msg: "{{ volume_state }}"
  when: config_toml is defined

- set_fact:
    _volume_path: "{{ volume_state.volumes[0]['Mountpoint'] }}"

- name: "Update file with given document: {{ _volume_path }}/config.toml"
  become: yes
  blockinfile:
    create: yes
    path: "{{ _volume_path }}/config.toml"
    block: "{{ config_toml }}"
  when: config_toml is defined

- name: "Create the gitlab_runner container"
  become: yes
  become_user: root
  containers.podman.podman_container:
    name: "gitlab-runner"
    state: started
    restart_policy: always
    image: "docker.io/gitlab/gitlab-runner:latest"
    privileged: true
    env:
      DOCKER_HOST: "unix:///var/run/podman/podman.sock"
    volumes:
      - "/run/podman/podman.sock:/var/run/podman/podman.sock"
      - "gitlab-runner-config:/etc/gitlab-runner"
