---
- name: "Install Podman and dependencies"
  become: yes
  dnf:
    name:
      - podman
      - libselinux-python3

- name: "Enable Podman socket"
  become: yes
  systemd:
    name: "podman"
    state: started
    enabled: yes
    daemon_reload: yes
