---
- name: Converge
  hosts: all
  roles:
    - role: gitlab_runner
  vars:
    config_toml: |
      concurrent = 1
      check_interval = 0

      [session_server]
        session_timeout = 1800

      [[runners]]
        name = "gitlan-runnner-podman"
        url = "https://some.gitlab.example.com/"
        token = "dr00ls"
        executor = "docker"
        [runners.custom_build_dir]
        [runners.cache]
          [runners.cache.s3]
          [runners.cache.gcs]
          [runners.cache.azure]
        [runners.docker]
          tls_verify = false
          image = "quay.io/redhat-cop/ubi8-git:v1.0"
          privileged = false
          disable_entrypoint_overwrite = false
          oom_kill_disable = false
          disable_cache = false
          volumes = ["/cache"]
          shm_size = 0
          extra_hosts=["some.ldap:127.0.0.1"]
