---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - include_tasks: "tests/user.yml"
    - include_tasks: "tests/podman.yml"
    - include_tasks: "tests/gitlab_runner.yml"
